In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype

dtype('int64')

In [16]:
a2.dtype, a3.dtype

(dtype('float64'), dtype('int64'))

In [17]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [18]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [21]:
# Create a DataFrame from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [22]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [23]:
sample_array.dtype

dtype('int64')

In [27]:
ones = np.ones())
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
ones.dtype

dtype('float64')

In [31]:
type(ones)

numpy.ndarray

In [33]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
range_array = np.arange(0, 10, 2)

In [42]:
range_array

array([0, 2, 4, 6, 8])

In [41]:
random_array = np.random.randint((10, 12))
random_array

array([8, 2])

# random_array_seed

In [50]:
np.random.seed(6)
               
random_array_2 = np.random.randint(5, 99, (3, 3))
random_array_2

array([[15, 78, 89],
       [84, 85, 67],
       [30,  6, 80]])

## 3. Viewing arrays and matrices

In [51]:
np.unique(random_array_2)

array([ 6, 15, 30, 67, 78, 80, 84, 85, 89])

In [52]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [57]:
a1[0], a2[0], a3[0]

(1,
 array([1. , 2. , 3.3]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [60]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [80]:
a4 = np.random.randint(10, size=(2, 3, 3, 5))
# a4 = np.random.Generator.randint()
a4

array([[[[3, 4, 7, 9, 2],
         [6, 1, 2, 3, 3],
         [2, 1, 0, 5, 4]],

        [[3, 4, 0, 4, 6],
         [1, 8, 2, 4, 3],
         [5, 4, 5, 5, 6]],

        [[7, 7, 3, 3, 2],
         [2, 9, 4, 5, 1],
         [5, 6, 7, 3, 1]]],


       [[[7, 4, 3, 2, 7],
         [9, 4, 9, 9, 0],
         [9, 4, 0, 0, 4]],

        [[4, 3, 4, 9, 4],
         [6, 7, 0, 5, 7],
         [5, 2, 1, 1, 1]],

        [[6, 7, 6, 4, 3],
         [1, 0, 9, 6, 7],
         [4, 0, 9, 6, 2]]]])

In [81]:
a4.shape, a4.ndim, a4.dtype

((2, 3, 3, 5), 4, dtype('int64'))

In [85]:
# Get the first 4 numbers of the inner most array
a4[1, 2, 0, :4]

array([6, 7, 6, 4])

In [88]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :1, :4]

array([[[[3, 4, 7, 9]],

        [[3, 4, 0, 4]],

        [[7, 7, 3, 3]]],


       [[[7, 4, 3, 2]],

        [[4, 3, 4, 9]],

        [[6, 7, 6, 4]]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [90]:
a1

array([1, 2, 3])

In [94]:
ones

array([1., 1., 1.])

In [95]:
a1 + ones

array([2., 3., 4.])

In [96]:
a1 - ones

array([0., 1., 2.])

In [97]:
a1 * ones

array([1., 2., 3.])

In [100]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [101]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [103]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [104]:
a1 * a3

array([[[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]],

       [[10, 22, 36],
        [13, 28, 45],
        [16, 34, 54]]])

In [106]:
a2[:,:,None] * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [107]:
a1 / ones

array([1., 2., 3.])

In [108]:
 zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [109]:
a1 / zeros

/tmp/ipykernel_144759/2373651089.py:1: RuntimeWarning: divide by zero encountered in divide
  a1 / zeros


array([[inf, inf, inf],
       [inf, inf, inf]])

In [110]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [112]:
a2 ** 3

array([[  1.   ,   8.   ,  35.937],
       [ 64.   , 125.   , 274.625]])

In [113]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [114]:
np.exp(a2)

array([[  2.71828183,   7.3890561 ,  27.11263892],
       [ 54.59815003, 148.4131591 , 665.14163304]])

In [115]:
np.log(a2)

array([[0.        , 0.69314718, 1.19392247],
       [1.38629436, 1.60943791, 1.87180218]])

### Aggregation

In [117]:
my_list = [1, 2, 3]
list_sum = sum(my_list)
list_sum

6

In [118]:
a1

array([1, 2, 3])

Use Python's methods `sum()` on Python datatypes and use NumPy's methods on NumPy arrays `np.sum()`

In [123]:
# Create a massive Numpy array
np.random.seed(19)
massive_array = np.random.random(10000)
massive_array.size

10000

In [124]:
massive_array

array([0.0975336 , 0.76124972, 0.24693797, ..., 0.33263289, 0.18760637,
       0.84132225])

In [125]:
massive_array[:10]

array([0.0975336 , 0.76124972, 0.24693797, 0.13813169, 0.33144656,
       0.08299957, 0.67197708, 0.8065938 , 0.98274191, 0.63566073])

In [126]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

2.38 ms ± 302 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
15.2 µs ± 1.27 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [127]:
np.mean(a2)

3.6333333333333333

In [128]:
np.max(a2)

6.5

In [132]:
# Standard deviation = a measure of how spread out a group of numbers is
# from the mean
np.std(a2), np.sqrt(np.var(a2))


(1.8226964152656422, 1.8226964152656422)

In [130]:
# Variance = measure of the average degree to which each number
# is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224