In [5]:
import numpy as np

## DataTypes & Attributes

In [6]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

array([1, 2, 3])

In [7]:
type(a1)

In [8]:
a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [9]:
a2

In [10]:
a3

In [11]:
a1.shape

In [12]:
a2.shape

In [13]:
a3.shape

In [14]:
a1.ndim, a2.ndim, a3.ndim

In [15]:
a1.dtype

In [16]:
a2.dtype, a3.dtype

In [17]:
a1.size, a2.size, a3.size

In [18]:
type(a1), type(a2), type(a3)

In [19]:
# Create a DataFrame from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

## 2. Creating arrays

In [20]:
sample_array = np.array([1, 2, 3])
sample_array

In [21]:
sample_array.dtype

In [22]:
ones = np.ones())
ones

In [ ]:
ones.dtype

In [ ]:
type(ones)

In [ ]:
zeros = np.zeros((2,3))
zeros

In [ ]:
range_array = np.arange(0, 10, 2)

In [ ]:
range_array

In [ ]:
random_array = np.random.randint((10, 12))
random_array

# random_array_seed

In [ ]:
np.random.seed(6)
               
random_array_2 = np.random.randint(5, 99, (3, 3))
random_array_2

## 3. Viewing arrays and matrices

In [ ]:
np.unique(random_array_2)

In [ ]:
a1, a2, a3

In [ ]:
a1[0], a2[0], a3[0]

In [ ]:
a3[:2, :2, :2]

In [ ]:
a4 = np.random.randint(10, size=(2, 3, 3, 5))
# a4 = np.random.Generator.randint()
a4

In [ ]:
a4.shape, a4.ndim, a4.dtype

In [ ]:
# Get the first 4 numbers of the inner most array
a4[1, 2, 0, :4]

In [ ]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :1, :4]

## 4. Manipulating & comparing arrays

### Arithmetic

In [ ]:
a1

In [ ]:
ones

In [ ]:
a1 + ones

In [ ]:
a1 - ones

In [ ]:
a1 * ones

In [ ]:
a2

In [ ]:
a1 * a2

In [ ]:
a3

In [ ]:
a1 * a3

In [ ]:
a2[:,:,None] * a3

In [ ]:
a1 / ones

In [ ]:
 zeros

In [ ]:
a1 / zeros

In [ ]:
a2

In [ ]:
a2 ** 3

In [ ]:
np.square(a2)

In [ ]:
np.exp(a2)

In [ ]:
np.log(a2)

### Aggregation

In [ ]:
my_list = [1, 2, 3]
list_sum = sum(my_list)
list_sum

In [ ]:
a1

Use Python's methods `sum()` on Python datatypes and use NumPy's methods on NumPy arrays `np.sum()`

In [ ]:
# Create a massive Numpy array
np.random.seed(19)
massive_array = np.random.random(10000)
massive_array.size

In [ ]:
massive_array

In [ ]:
massive_array[:10]

In [ ]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
# Standard deviation = a measure of how spread out a group of numbers is
# from the mean
np.std(a2), np.sqrt(np.var(a2))


In [ ]:
# Variance = measure of the average degree to which each number
# is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

In [ ]:
# Demo of std and var
high_var_array = np.array([1, 100, 300, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

## Reshaping & transposing

In [ ]:
a2, a3

In [ ]:
a2.shape, a3.shape

In [ ]:
a2 * a3

In [ ]:
 a2.reshape(2, 3, 1).shape

In [ ]:
a2

In [ ]:
a2_reshape = a2.reshape(2, 3, 1)

In [ ]:
a2_reshape * a3

In [ ]:
# Transpose = swittches the axis'
a2, a2.T

In [ ]:
a3.shape, a3.T.shape

In [ ]:
a3, a3.T

## Dot product

In [ ]:
np.random.seed(0)
mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [ ]:
mat1, mat2, mat1.shape, mat2.shape

In [ ]:
# Element-wise multiplication (Hadamard product)
mat1 * mat2

In [ ]:
# Dot product

np.dot(mat1, mat2.T)

## Exercise

In [ ]:
# Creating tables with pandas

In [ ]:
prices = pd.Series([10, 8, 12])
prices

In [ ]:
nut_butter_sales = pd.DataFrame({
    "Almond butter": [2, 9, 11, 13, 15],
    "Peanut butter": [7, 4, 14, 13, 18],
    "Cashew butter": [1, 16, 18, 16, 9],
})
nut_butter_sales

In [ ]:
index_mapping = {0: "Mon", 1: "Tue", 2: "Wed", 3: "Thu", 4: "Fri"}
nut_butter_sales.rename(index=index_mapping, inplace=True)

In [ ]:
nut_butter_sales

In [ ]:
prices.name = "Price"

In [ ]:
prices.index = ["Almond butter", "Peanut butter", "Cashew butter"]

In [ ]:
prices

In [ ]:
# Creating it as in the video

In [ ]:
np.random.seed(0)
# Number of jars sold
sales_amount = np.random.randint(20, size=(5,3))
sales_amount

In [ ]:
# Create weekly sales DataFrame
weekly_sales = pd.DataFrame(sales_amount,
                            index=["Mon", "Tue", "Wed", "Thu", "Fri"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

In [ ]:
# Create prices array
test_prices = np.array([10, 8, 12])
test_prices

In [ ]:
# Create prices DataFrame
prices_df = pd.DataFrame(test_prices.reshape(1, 3),
                         index=["Price"],
                         columns=["Almond butter", "Peanut butter", "Cashew butter"])
prices_df

In [ ]:
total_sales = np.dot(prices_df, weekly_sales.T)[0]
total_sales

In [ ]:
weekly_sales["Total ($)"] = total_sales

In [ ]:
weekly_sales

### Comparison Operators

In [24]:
a1, a2

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [25]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [26]:
bool_array = a1 >= a2

In [27]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [28]:
a1 > 5

array([False, False, False])

In [29]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

In [32]:
b1 = np.array([2, 5 ,123123])

In [33]:
b1 == a2

array([[False, False, False],
       [False,  True, False]])

# 5. Sorting arrays

In [36]:
random_array = np.random.randint(10, size=(3,5))
random_array

array([[9, 7, 1, 1, 4],
       [1, 1, 2, 7, 2],
       [9, 7, 3, 1, 8]])

In [35]:
random_array.shape

(3, 5)

In [37]:
np.sort(random_array)

array([[1, 1, 4, 7, 9],
       [1, 1, 2, 2, 7],
       [1, 3, 7, 8, 9]])

In [38]:
np.argsort(random_array)

array([[2, 3, 4, 1, 0],
       [0, 1, 2, 4, 3],
       [3, 2, 1, 4, 0]])

In [41]:
np.argmin(random_array, axis=0)

array([1, 1, 0, 0, 1])

In [42]:
np.argmax(random_array, axis=1)

array([0, 3, 0])

# 6. Practical Example - NumPy in Action!!!!

![Image Description](panda.png)


In [53]:
# Turn an image into a NumPy array
from matplotlib.image import imread

panda = imread("images/panda.png")
type(panda)

numpy.ndarray

In [54]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [57]:
car = imread("images/car-photo.png")

In [58]:
car.size, car.shape, car.ndim

(991300, (431, 575, 4), 3)

In [59]:
dog = imread("images/dog-photo.png")

In [61]:
dog.size, dog.shape, dog.ndim

(993600, (432, 575, 4), 3)